x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: '$TAG'
  publishedVersionMetadata:
    releaseNote: >-
      Initial marketplace release.
    releaseTypes:
      - Feature
    recommended: false

  deployerServiceAccount:
    description: >
      Creates app resources, including the MyAppCustomResource CRD.
    roles:
    - type: ClusterRole
      rulesType: CUSTOM
      rules:
      - apiGroups: ['apiextensions.k8s.io']
        resources: ['customresourcedefinitions']
        verbs: ['*']

  images:
    controller:
      #'':
      properties:
        registry:
          type: REGISTRY
          default: $REGISTRY
        core.tag:
          type: TAG
        core.controller.image.repository:
          type: REPO_WITHOUT_REGISTRY

    enforcer:
      properties:
        core.enforcer.image.repository:
          type: REPO_WITHOUT_REGISTRY
        core.enforcer.image.tag:
          type: TAG

    manager:
      properties:
        core.manager.image.repository:
          type: REPO_WITHOUT_REGISTRY
        core.manager.image.tag:
          type: TAG

    updater:
      properties:
        core.cve.updater.image.repository:
          type: REPO_WITHOUT_REGISTRY
        core.cve.updater.image.tag:
          type: TAG

    scanner:
      properties:
        core.cve.scanner.image.repository:
          type: REPO_WITHOUT_REGISTRY
        core.cve.scanner.image.tag:
          type: TAG

# clusterConstraints:
#   resources:
#     - replicas: 3
#       requests:
#         cpu: 2000m
#         memory: 8192Mi
#   istio:
#     type: OPTIONAL

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    default: neuvector
    x-google-marketplace:
      type: NAMESPACE
  core.bootstrapPassword:
    title: User-specified admin password
    description: The password to be used for admin login.
    maxLength: 32
    type: string
    x-google-marketplace:
      type: MASKED_FIELD
  core.global.gcloud.serviceAccount:
    type: string
    title: Neuvector CSP Adapter Service Account
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          Manages CSP Adapter resources
        roles:
        - type: ClusterRole
          metadata:
            name: neuvector-csp-adapter-cluster-role
          rulesType: CUSTOM
          rules:
          - apiGroups: ["susecloud.net"]
            resources:
            - "cspadapterusagerecords"
            resourceNames:
            - "neuvector-usage"
            verbs:
            - "get"
        - type: ClusterRole
          metadata:
            name: neuvector-binding-csp-usages
          rulesType: CUSTOM
          rules:
          - apiGroups: ["susecloud.net"]
            resources:
            - "cspadapterusagerecords"
            verbs:
            - "get"
            - "create"
            - "update"
            - "delete"
        - type: ClusterRole
          metadata:
            name: neuvector-csp-adapter-role
          rulesType: CUSTOM
          rules:
          - apiGroups: [""]
            resources:
            - "secrets"
            resourceNames:
            - "csp-adapter-cache"
            verbs:
            - "*"
          - apiGroups: [""]
            resources:
            - "secrets"
            verbs:
            - "create"
          - apiGroups: [""]
            resources:
            - "configmaps"
            resourceNames:
            - "csp-config"
            verbs:
            - "*"
          - apiGroups: [""]
            resources:
            - "configmaps"
            resourceNames:
            - "metering-archive"
            verbs:
            - "*"
          - apiGroups: [""]
            resources:
            - "configmaps"
            verbs:
            - "create"
  core.serviceAccount:
    type: string
    title: Neuvector Service Account
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          Manages cluster wide resources
        roles:
        - type: ClusterRole
          metadata:
            name: neuvector-binding-rbac
          rulesType: CUSTOM
          rules:
          - apiGroups: ["rbac.authorization.k8s.io"]
            resources:
            - "rolebindings"
            - "roles"
            - "clusterrolebindings"
            - "clusterroles"
            verbs:
            - "get"
            - "list"
            - "watch"
          - apiGroups: ["image.openshift.io"]
            resources:
            - "imagestreams"
            verbs:
            - "get"
            - "list"
            - "watch"
        - type: ClusterRole
          metadata:
            name: neuvector-binding-app
          rulesType: CUSTOM
          rules:

          - apiGroups: [""]
            resources:
            - "nodes"
            - "pods"
            - "services"
            - "namespaces"

            verbs:
            - "get"
            - "list"
            - "watch"
            - "update"
        - type: ClusterRole
          metadata:
            name: neuvector-binding-admission
          rulesType: CUSTOM
          rules:

          - apiGroups: ["admissionregistration.k8s.io"]
            resources:
            - "validatingwebhookconfigurations"
            - "mutatingwebhookconfigurations"

            verbs:
            - "get"
            - "list"
            - "watch"
            - "create"
            - "update"
            - "delete"
        - type: ClusterRole
          metadata:
            name: neuvector-binding-co
          rulesType: CUSTOM
          rules:

          - apiGroups: ["config.openshift.io"]
            resources:
            - "clusteroperators"

            verbs:
            - "get"
            - "list"
        - type: ClusterRole
          metadata:
            name: neuvector-binding-customresourcedefinition
          rulesType: CUSTOM
          rules:

          - apiGroups: ["apiextensions.k8s.io"]
            resources:
            - "customresourcedefinitions"

            verbs:
            - "update"
            - "watch"
            - "create"
            - "get"
        - type: ClusterRole
          metadata:
            name: neuvector-binding-nvsecurityrules
          rulesType: CUSTOM
          rules:

          - apiGroups: ["neuvector.com"]
            resources:
            - "nvsecurityrules"
            - "nvclustersecurityrules"

            verbs:
            - "get"
            - "list"
            - "delete"
        - type: ClusterRole
          metadata:
            name: neuvector-binding-nvdlpsecurityrules
          rulesType: CUSTOM
          rules:

          - apiGroups: ["neuvector.com"]
            resources:
            - "nvdlpsecurityrules"

            verbs:
            - "get"
            - "list"
            - "delete"
        - type: ClusterRole
          metadata:
            name: neuvector-binding-nvadmissioncontrolsecurityrules
          rulesType: CUSTOM
          rules:

          - apiGroups: ["neuvector.com"]
            resources:
            - "nvadmissioncontrolsecurityrules"

            verbs:
            - "get"
            - "list"
            - "delete"
        - type: ClusterRole
          metadata:
            name: neuvector-binding-nvwafsecurityrules
          rulesType: CUSTOM
          rules:

          - apiGroups: ["neuvector.com"]
            resources:
            - "nvwafsecurityrules"

            verbs:
            - "get"
            - "list"
            - "delete"
        - type: ClusterRole
          metadata:
            name: neuvector-binding-nvcomplianceprofiles
          rulesType: CUSTOM
          rules:

          - apiGroups: ["neuvector.com"]
            resources:
            - "nvcomplianceprofiles"

            verbs:
            - "get"
            - "list"
            - "delete"
        - type: ClusterRole
          metadata:
            name: neuvector-binding-nvvulnerabilityprofiles
          rulesType: CUSTOM
          rules:

          - apiGroups: ["neuvector.com"]
            resources:
            - "nvvulnerabilityprofiles"

            verbs:
            - "get"
            - "list"
            - "delete"
        - type: ClusterRole
          metadata:
            name: neuvector-binding-secret
          rulesType: CUSTOM
          rules:

          - apiGroups: [""]
            resources:
            - "secrets"

            verbs:
            - "get"
            - "list"
            - "watch"
        - type: ClusterRole
          metadata:
            name: neuvector-binding-lease
          rulesType: CUSTOM
          rules:

          - apiGroups: ["coordination.k8s.io"]
            resources:
            - "leases"

            verbs:
            - "create"
            - "get"
            - "update"
        - type: ClusterRole
          metadata:
            name: neuvector-binding-job-creation
          rulesType: CUSTOM
          rules:

          - apiGroups: ["batch"]
            resources:
            - "jobs"

            verbs:
            - "create"
            - "get"
            - "delete"
          - apiGroups: ["batch"]
            resources:
            - "cronjobs"
            - "cronjobs/finalizers"

            verbs:
            - "update"
            - "patch"
        - type: ClusterRole
          metadata:
            name: neuvector-binding-cert-upgrader
          rulesType: CUSTOM
          rules:

          - apiGroups: [""]
            resources:
            - "secrets"

            verbs:
            - "get"
            - "update"
            - "list"
            - "watch"
          - apiGroups: [""]
            resources:
            - "pods"

            verbs:
            - "get"
            - "list"
          - apiGroups: ["apps"]
            resources:
            - "deployments"
            - "daemonsets"

            verbs:
            - "get"
            - "list"
            - "watch"
          - apiGroups: ["batch"]
            resources:
            - "cronjobs"

            verbs:
            - "update"
            - "get"

required:
- name
- namespace
