#!/bin/bash
set -e  # fail if any command fails
set -u  # fail if any variable is undefined

# set up chart area.
git clone --branch ${2} ${1}
cp -a neuvector-helm-gks/charts/. neuvector-prime-byos/charts/
cp -a chart/${3}/. /tmp/chart
