x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      Initial marketplace release.
    releaseTypes:
      - Feature
    recommended: false

  images:
    '':
      properties:
        global.images.rancher_prime_byos.image:
          type: REPO_WITHOUT_REGISTRY
          default: rancher-prime-byos
        global.images.rancher_prime_byos.registry:
          type: REGISTRY
          default: $REGISTRY
        global.images.rancher_prime_byos.tag:
          type: TAG
          default: $TAG

    rancher:
      properties:
        global.images.rancher.image:
          type: REPO_WITHOUT_REGISTRY
          default: rancher-prime-byos/rancher
        global.images.rancher.registry:
          type: REGISTRY
          default: $REGISTRY
        global.images.rancher.tag:
          type: TAG
          default: $TAG

    shell:
      properties:
        global.images.rancher_postdelete.image:
          type: REPO_WITHOUT_REGISTRY
          default: rancher-prime-byos/shell
        global.images.rancher_postdelete.registry:
          type: REGISTRY
          default: $REGISTRY
        global.images.rancher_postdelete.tag:
          type: TAG
          default: v0.1.21

    mirrored-bci-micro:
      properties:
        global.images.rancher_auditlog.image:
          type: REPO_WITHOUT_REGISTRY
          default: rancher-prime-byos/mirrored-bci-micro
        global.images.rancher_autitlog.registry:
          type: REGISTRY
          default: $REGISTRY
        global.images.rancher_autitlog.tag:
          type: TAG
          default: "15.4.14.3"

    cert-manager-controller:
      properties:
        global.images.cert_manager.image:
          type: REPO_WITHOUT_REGISTRY
          default: rancher-prime-byos/cert-manager-controller
        global.images.cert_manager.registry:
          type: REGISTRY
          default: $REGISTRY
        global.images.cert_manager.tag:
          type: TAG
          default: v1.12.3

    cert-manager-webhook:
      properties:
        global.images.cert_manager_webhook.image:
          type: REPO_WITHOUT_REGISTRY
          default: rancher-prime-byos/cert-manager-webhook
        global.images.cert_manager_webhook.registry:
          type: REGISTRY
          default: $REGISTRY
        global.images.cert_manager_webhook.tag:
          type: TAG
          default: v1.12.3

    cert-manager-cainjector:
      properties:
        global.images.cert_manager_cainjector.image:
          type: REPO_WITHOUT_REGISTRY
          default: rancher-prime-byos/cert-manager-cainjector
        global.images.cert_manager_cainjector.registry:
          type: REGISTRY
          default: $REGISTRY
        global.images.cert_manager_cainjector.tag:
          type: TAG
          default: v1.12.3

    cert-manager-acmesolver:
      properties:
        global.images.cert_manager_acmesolver.image:
          type: REPO_WITHOUT_REGISTRY
          default: rancher-prime-byos/cert-manager-acmesolver
        global.images.cert_manager_acmesolver.registry:
          type: REGISTRY
          default: $REGISTRY
        global.images.cert_manager_acmesolver.tag:
          type: TAG
          default: v1.12.3

    cert-manager-ctl:
      properties:
        global.images.cert_manager_startupapicheck.image:
          type: REPO_WITHOUT_REGISTRY
          default: rancher-prime-byos/cert-manager-ctl
        global.images.cert_manager_startupapicheck.registry:
          type: REGISTRY
          default: $REGISTRY
        global.images.cert_manager_startupapicheck.tag:
          type: TAG
          default: v1.12.3

    controller:
      properties:
        global.images.ingress_nginx_controller.image:
          type: REPO_WITHOUT_REGISTRY
          default: rancher-prime-byos/controller
        global.images.ingress_nginx_controller.registry:
          type: REGISTRY
          default: $REGISTRY
        global.images.ingress_nginx_controller.tag:
          type: TAG
          default: v1.9.0

    kube-webhook-certgen:
      properties:
        global.images.kube_webhook_certgen.image:
          type: REPO_WITHOUT_REGISTRY
          default: rancher-prime-byos/kube_webhook_certgen
        global.images.kube_webhook_certgen.registry:
          type: REGISTRY
          default: $REGISTRY
        global.images.kube_webhook_certgen.tag:
          type: TAG
          default: v20230407

  deployerServiceAccount:
    description: >
      Runs the Rancher cloud installer, setting up the required
      services.
    roles:
    # NOTE: Placeholder definition, please update/remove as appropriate
    - type: ClusterRole
      rulesType: PREDEFINED
      rulesFromRoleName: view

clusterConstraints:
  k8sVersion: "<1.27"
#   resources:
#     - replicas: 3
#       requests:
#         cpu: 2000m
#         memory: 8192Mi
#   istio:
#     type: OPTIONAL

properties:
  name:
    type: string
    default: rancher-prime-byos
    x-google-marketplace:
      type: NAME

  namespace:
    type: string
    default: rancher-prime-byos-ns
    x-google-marketplace:
      type: NAMESPACE

  rancherHostname:
    type: string

  rancherServerURL:
    type: string

  rancherReplicas:
    type: int
    default: 1

  rancherBootstrapPassword:
    type: string

  rancherIngressClassName:
    type: string
    default: nginx

  serviceAccount.name:
    type: string
    title: Rancher Service Account
    default: rancher-prime-byos-sa
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          Manages cluster wide resources
        roles:
        # NOTE: Placeholder definition, please update/remove as appropriate
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: view

required:
- name
- namespace
